- name: sdebug
  raw: DEBUG = $:False$ $END$
- name: sdebug_propagate_exceptions
  raw: DEBUG_PROPAGATE_EXCEPTIONS = $:False$ $END$
- name: suse_etags
  raw: USE_ETAGS = $:False$ $END$
- name: sadmins
  raw: ADMINS = [('$:USER$', '$:EMAIL$'), ]$END$
- name: sinternal_ips
  raw: INTERNAL_IPS = $:[]$ $END$
- name: sallowed_hosts
  raw: ALLOWED_HOSTS = $:[]$ $END$
- name: stime_zone
  raw: TIME_ZONE = '$:America/Chicago$' $END$
- name: suse_tz
  raw: USE_TZ = $:False$ $END$
- name: slanguage_code
  raw: LANGUAGE_CODE = '$:en-us$' $END$
- name: slanguages_bidi
  raw: LANGUAGES_BIDI = ["he", "ar", "fa", "ur", $$] $END$
- name: suse_i18n
  raw: USE_I18N = $:True$ $END$
- name: slocale_paths
  raw: LOCALE_PATHS = $:[]$ $END$
- name: slanguage_cookie_name
  raw: LANGUAGE_COOKIE_NAME = '$:django_language$' $END$
- name: slanguage_cookie_age
  raw: LANGUAGE_COOKIE_AGE = $:None$ $END$
- name: slanguage_cookie_domain
  raw: LANGUAGE_COOKIE_DOMAIN = $:None$ $END$
- name: slanguage_cookie_path
  raw: LANGUAGE_COOKIE_PATH = '$:/$' $END$
- name: suse_l10n
  raw: USE_L10N = $:False$ $END$
- name: smanagers
  raw: MANAGERS = $:ADMINS$ $END$
- name: sdefault_content_type
  raw: DEFAULT_CONTENT_TYPE = '$:text/html$' $END$
- name: sdefault_charset
  raw: DEFAULT_CHARSET = '$:utf-8$' $END$
- name: sfile_charset
  raw: FILE_CHARSET = '$:utf-8$' $END$
- name: sserver_email
  raw: SERVER_EMAIL = '$:root@localhost$' $END$
- name: sdatabase_routers
  raw: DATABASE_ROUTERS = $:[]$ $END$
- name: semail_backend
  raw: EMAIL_BACKEND = '$:django.core.mail.backends.smtp.EmailBackend$' $END$
- name: semail_host
  raw: EMAIL_HOST = '$:localhost$' $END$
- name: semail_port
  raw: EMAIL_PORT = $:25$ $END$
- name: semail_host_user
  raw: EMAIL_HOST_USER = '$:$' $END$
- name: semail_host_password
  raw: EMAIL_HOST_PASSWORD = '$:$' $END$
- name: semail_use_tls
  raw: EMAIL_USE_TLS = $:False$ $END$
- name: semail_use_ssl
  raw: EMAIL_USE_SSL = $:False$ $END$
- name: semail_ssl_certfile
  raw: EMAIL_SSL_CERTFILE = $:None$ $END$
- name: semail_ssl_keyfile
  raw: EMAIL_SSL_KEYFILE = $:None$ $END$
- name: semail_timeout
  raw: EMAIL_TIMEOUT = $:None$ $END$
- name: sinstalled_apps
  raw: INSTALLED_APPS = $:[]$ $END$
- name: sdefault_from_email
  raw: DEFAULT_FROM_EMAIL = '$:webmaster@localhost$' $END$
- name: semail_subject_prefix
  raw: EMAIL_SUBJECT_PREFIX = '$:[Django] $' $END$
- name: sappend_slash
  raw: APPEND_SLASH = $:True$ $END$
- name: sprepend_www
  raw: PREPEND_WWW = $:False$ $END$
- name: sforce_script_name
  raw: FORCE_SCRIPT_NAME = $:None$ $END$
- name: sdisallowed_user_agents
  raw: DISALLOWED_USER_AGENTS = $:[]$ $END$
- name: sabsolute_url_overrides
  raw: ABSOLUTE_URL_OVERRIDES = $:{}$ $END$
- name: signorable_404_urls
  raw: IGNORABLE_404_URLS = $:[]$ $END$
- name: ssecret_key
  raw: SECRET_KEY = '$:$' $END$
- name: sdefault_file_storage
  raw: DEFAULT_FILE_STORAGE = '$:django.core.files.storage.FileSystemStorage$' $END$
- name: smedia_root
  raw: MEDIA_ROOT = '$:$' $END$
- name: smedia_url
  raw: MEDIA_URL = '$:/media/$' $END$
- name: sstatic_root
  raw: STATIC_ROOT = $:None$ $END$
- name: sstatic_url
  raw: STATIC_URL = '$:/static/$' $END$
- name: sfile_upload_max_memory_size
  raw: FILE_UPLOAD_MAX_MEMORY_SIZE = $:2621440$ $END$
- name: sdata_upload_max_memory_size
  raw: DATA_UPLOAD_MAX_MEMORY_SIZE = $:2621440$ $END$
- name: sdata_upload_max_number_fields
  raw: DATA_UPLOAD_MAX_NUMBER_FIELDS = $:1000$ $END$
- name: sfile_upload_temp_dir
  raw: FILE_UPLOAD_TEMP_DIR = $:None$ $END$
- name: sfile_upload_permissions
  raw: FILE_UPLOAD_PERMISSIONS = $:None$ $END$
- name: sfile_upload_directory_permissions
  raw: FILE_UPLOAD_DIRECTORY_PERMISSIONS = $:None$ $END$
- name: sformat_module_path
  raw: FORMAT_MODULE_PATH = $:None$ $END$
- name: sdate_format
  raw: DATE_FORMAT = '$:N j, Y$' $END$
- name: sdatetime_format
  raw: DATETIME_FORMAT = '$:N j, Y, P$' $END$
- name: stime_format
  raw: TIME_FORMAT = '$:P$' $END$
- name: syear_month_format
  raw: YEAR_MONTH_FORMAT = '$:F Y$' $END$
- name: smonth_day_format
  raw: MONTH_DAY_FORMAT = '$:F j$' $END$
- name: sshort_date_format
  raw: SHORT_DATE_FORMAT = '$:m/d/Y$' $END$
- name: sshort_datetime_format
  raw: SHORT_DATETIME_FORMAT = '$:m/d/Y P$' $END$
- name: sfirst_day_of_week
  raw: FIRST_DAY_OF_WEEK = $:0$ $END$
- name: sdecimal_separator
  raw: DECIMAL_SEPARATOR = '$:.$' $END$
- name: suse_thousand_separator
  raw: USE_THOUSAND_SEPARATOR = $:False$ $END$
- name: snumber_grouping
  raw: NUMBER_GROUPING = $:0$ $END$
- name: sthousand_separator
  raw: THOUSAND_SEPARATOR = '$:,$' $END$
- name: sdefault_tablespace
  raw: DEFAULT_TABLESPACE = '$:$' $END$
- name: sdefault_index_tablespace
  raw: DEFAULT_INDEX_TABLESPACE = '$:$' $END$
- name: sx_frame_options
  raw: X_FRAME_OPTIONS = '$:SAMEORIGIN$' $END$
- name: suse_x_forwarded_host
  raw: USE_X_FORWARDED_HOST = $:False$ $END$
- name: suse_x_forwarded_port
  raw: USE_X_FORWARDED_PORT = $:False$ $END$
- name: swsgi_application
  raw: WSGI_APPLICATION = $:None$ $END$
- name: ssecure_proxy_ssl_header
  raw: SECURE_PROXY_SSL_HEADER = $:None$ $END$
- name: ssession_cache_alias
  raw: SESSION_CACHE_ALIAS = '$:default$' $END$
- name: ssession_cookie_name
  raw: SESSION_COOKIE_NAME = '$:sessionid$' $END$
- name: ssession_cookie_age
  raw: SESSION_COOKIE_AGE = $:60 * 60 * 24 * 7 * 2$ $END$
- name: ssession_cookie_domain
  raw: SESSION_COOKIE_DOMAIN = $:None$ $END$
- name: ssession_cookie_secure
  raw: SESSION_COOKIE_SECURE = $:False$ $END$
- name: ssession_cookie_path
  raw: SESSION_COOKIE_PATH = '$:/$' $END$
- name: ssession_cookie_httponly
  raw: SESSION_COOKIE_HTTPONLY = $:True$ $END$
- name: ssession_save_every_request
  raw: SESSION_SAVE_EVERY_REQUEST = $:False$ $END$
- name: ssession_expire_at_browser_close
  raw: SESSION_EXPIRE_AT_BROWSER_CLOSE = $:False$ $END$
- name: ssession_engine
  raw: SESSION_ENGINE = '$:django.contrib.sessions.backends.db$' $END$
- name: ssession_file_path
  raw: SESSION_FILE_PATH = $:None$ $END$
- name: ssession_serializer
  raw: SESSION_SERIALIZER = '$:django.contrib.sessions.serializers.JSONSerializer$' $END$
- name: scache_middleware_key_prefix
  raw: CACHE_MIDDLEWARE_KEY_PREFIX = '$:$' $END$
- name: scache_middleware_seconds
  raw: CACHE_MIDDLEWARE_SECONDS = $:600$ $END$
- name: scache_middleware_alias
  raw: CACHE_MIDDLEWARE_ALIAS = '$:default$' $END$
- name: sauth_user_model
  raw: AUTH_USER_MODEL = '$:auth.User$' $END$
- name: sauthentication_backends
  raw: AUTHENTICATION_BACKENDS = $:['django.contrib.auth.backends.ModelBackend']$ $END$
- name: slogin_url
  raw: LOGIN_URL = '$:/accounts/login/$' $END$
- name: slogin_redirect_url
  raw: LOGIN_REDIRECT_URL = '$:/accounts/profile/$' $END$
- name: slogout_redirect_url
  raw: LOGOUT_REDIRECT_URL = $:None$ $END$
- name: spassword_reset_timeout_days
  raw: PASSWORD_RESET_TIMEOUT_DAYS = $:3$ $END$
- name: sauth_password_validators
  raw: AUTH_PASSWORD_VALIDATORS = $:[]$ $END$
- name: ssigning_backend
  raw: SIGNING_BACKEND = '$:django.core.signing.TimestampSigner$' $END$
- name: scsrf_failure_view
  raw: CSRF_FAILURE_VIEW = '$:django.views.csrf.csrf_failure$' $END$
- name: scsrf_cookie_name
  raw: CSRF_COOKIE_NAME = '$:csrftoken$' $END$
- name: scsrf_cookie_age
  raw: CSRF_COOKIE_AGE = $:60 * 60 * 24 * 7 * 52$ $END$
- name: scsrf_cookie_domain
  raw: CSRF_COOKIE_DOMAIN = $:None$ $END$
- name: scsrf_cookie_path
  raw: CSRF_COOKIE_PATH = '$:/$' $END$
- name: scsrf_cookie_secure
  raw: CSRF_COOKIE_SECURE = $:False$ $END$
- name: scsrf_cookie_httponly
  raw: CSRF_COOKIE_HTTPONLY = $:False$ $END$
- name: scsrf_header_name
  raw: CSRF_HEADER_NAME = '$:HTTP_X_CSRFTOKEN$' $END$
- name: scsrf_trusted_origins
  raw: CSRF_TRUSTED_ORIGINS = $:[]$ $END$
- name: smessage_storage
  raw: MESSAGE_STORAGE = '$:django.contrib.messages.storage.fallback.FallbackStorage$' $END$
- name: smessage_level
  raw: MESSAGE_LEVEL = $:messages.INFO$ $END$
- name: slogging_config
  raw: LOGGING_CONFIG = '$:logging.config.dictConfig$' $END$
- name: sdefault_exception_reporter_filter
  raw: DEFAULT_EXCEPTION_REPORTER_FILTER = '$:django.views.debug.SafeExceptionReporterFilter$' $END$
- name: stest_runner
  raw: TEST_RUNNER = '$:django.test.runner.DiscoverRunner$' $END$
- name: stest_non_serialized_apps
  raw: TEST_NON_SERIALIZED_APPS = $:[]$ $END$
- name: sfixture_dirs
  raw: FIXTURE_DIRS = [$:$] $END$
- name: sstaticfiles_dirs
  raw: STATICFILES_DIRS = [$:$] $END$
- name: sstaticfiles_storage
  raw: STATICFILES_STORAGE = '$:django.contrib.staticfiles.storage.StaticFilesStorage$' $END$
- name: smigration_modules
  raw: MIGRATION_MODULES = $:{}$ $END$
- name: ssilenced_system_checks
  raw: SILENCED_SYSTEM_CHECKS = $:[]$ $END$
- name: ssecure_browser_xss_filter
  raw: SECURE_BROWSER_XSS_FILTER = $:False$ $END$
- name: ssecure_content_type_nosniff
  raw: SECURE_CONTENT_TYPE_NOSNIFF = $:False$ $END$
- name: ssecure_hsts_include_subdomains
  raw: SECURE_HSTS_INCLUDE_SUBDOMAINS = $:False$ $END$
- name: ssecure_hsts_seconds
  raw: SECURE_HSTS_SECONDS = $:0$ $END$
- name: ssecure_redirect_exempt
  raw: SECURE_REDIRECT_EXEMPT = $:[]$ $END$
- name: ssecure_ssl_host
  raw: SECURE_SSL_HOST = $:None$ $END$
- name: ssecure_ssl_redirect
  raw: SECURE_SSL_REDIRECT = $:False$ $END$
- name: sroot_urlconf
  raw: ROOT_URLCONF = '$$'
- name: sserialization_modules
  raw: SERIALIZATION_MODULES = {'$:name$' '$:path.to.serializer$'}
- name: ssite_id
  raw: SITE_ID = $:None$
- name: scaches
  template: modifications/templates/settings/caches
- name: sdatabases
  template: modifications/templates/settings/databases
- name: sdatabase
  template: modifications/templates/settings/database
- name: sdatabasetest
  template: modifications/templates/settings/databasetest
- name: sdate_input_formats
  template: modifications/templates/settings/date_input_formats
- name: sdatetime_input_formats
  template: modifications/templates/settings/datetime_input_formats
- name: sfile_upload_handlers
  template: modifications/templates/settings/file_upload_handlers
- name: slanguages
  template: modifications/templates/settings/languages
- name: slogfilter
  template: modifications/templates/settings/logfilter
- name: slogfiltercallback
  template: modifications/templates/settings/logfiltercallback
- name: slogfilterdebugfalse
  template: modifications/templates/settings/logfilterdebugfalse
- name: slogfilterdebugtrue
  template: modifications/templates/settings/logfilterdebugtrue
- name: slogformatter
  template: modifications/templates/settings/logformatter
- name: slogformatterserver
  template: modifications/templates/settings/logformatterserver
- name: slogger
  template: modifications/templates/settings/logger
- name: slogging
  template: modifications/templates/settings/logging
- name: sloghandler
  template: modifications/templates/settings/loghandler
- name: sloghandleremail
  template: modifications/templates/settings/loghandleremail
- name: sloghandlerstream
  template: modifications/templates/settings/loghandlerstream
- name: smessage_tags
  template: modifications/templates/settings/message_tags
- name: smiddleware
  template: modifications/templates/settings/middleware
- name: smiddleware_classes
  template: modifications/templates/settings/middleware_classes
- name: spassword_hashers
  template: modifications/templates/settings/password_hashers
- name: sstatic_files_finders
  template: modifications/templates/settings/static_files_finders
- name: stemplates
  template: modifications/templates/settings/templates
- name: stime_input_formats
  template: modifications/templates/settings/time_input_formats